### ISSUE TITLE
import pytorch with rocm support will just crash on a CPU without AVX

### ISSUE THREAD

**Issue by echoidcf** [ROCm/pytorch#1216]
### 🐛 Describe the bug

rocm (rocrand or rocblas or something like that) defaultly use AVX instructions.
When they are loaded by torch with rocm support, just import torch will crash everything.
Because it will call a asm instruction called vxorps which is AVX, but if the CPU does not support AVX for example G4930 , BOOM!

I change my CPU from G4930 to i3 9100, everything goes well after that.

### Versions

As far as test, rocm 5.4.x and pytorch 2.0.0 at least has this problem.

**Comment by darren-amd** [comment]
Hi @echoidcf,

Just wanted to confirm your question: are you running into issues running pytorch due to Intel Celeron Processor G4930 lacking support for AVX, and instead are able to run on an Intel i3 9100?

Also wanted to confirm if you have an AMD GPU that you are running ROCm on?

**Comment by darren-amd** [comment]
Closing this ticket due to inactivity, please feel free to create another one if the issue persists, thanks!
