### ISSUE TITLE
Nod-ai/SHARK using ROCm 5.7 & 7900XTX causes errors in dmesg

### ISSUE THREAD

**Issue by briansp2020** [ROCm/pytorch#1284]
### 🐛 Describe the bug

When running https://github.com/nod-ai/SHARK using ROCm 5.7 and 7900XTX, I keep getting the following error message in dmesg.

```
[   90.648641] amdgpu 0000:2d:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:157 vmid:0 pasid:0, for process  pid 0 thread  pid 0)
[   90.648648] amdgpu 0000:2d:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0013 address=0xfe9fe000 flags=0x0000]
[   90.648686] amdgpu 0000:2d:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 10
[   90.648716] amdgpu 0000:2d:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0013 address=0xfe9fe000 flags=0x0020]
[   90.648740] amdgpu 0000:2d:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00000B3A
[   90.648783] amdgpu 0000:2d:00.0: amdgpu:      Faulty UTCL2 client ID: CPC (0x5)
[   90.648803] amdgpu 0000:2d:00.0: amdgpu:      MORE_FAULTS: 0x0
[   90.648818] amdgpu 0000:2d:00.0: amdgpu:      WALKER_ERROR: 0x5
[   90.648834] amdgpu 0000:2d:00.0: amdgpu:      PERMISSION_FAULTS: 0x3
[   90.648850] amdgpu 0000:2d:00.0: amdgpu:      MAPPING_ERROR: 0x1
[   90.648866] amdgpu 0000:2d:00.0: amdgpu:      RW: 0x0
[   91.806542] amdgpu 0000:2d:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0013 address=0xfe9fe000 flags=0x0020]
[   91.841566] amdgpu 0000:2d:00.0: amdgpu: [gfxhub] page fault (src_id:0 ring:157 vmid:0 pasid:0, for process  pid 0 thread  pid 0)
[   91.841597] amdgpu 0000:2d:00.0: amdgpu:   in page starting at address 0x0000000000000000 from client 10
[   91.841614] amdgpu 0000:2d:00.0: amdgpu: GCVM_L2_PROTECTION_FAULT_STATUS:0x00000B3A
[   91.841627] amdgpu 0000:2d:00.0: amdgpu:      Faulty UTCL2 client ID: CPC (0x5)
[   91.841630] amdgpu 0000:2d:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0013 address=0xfe9fe000 flags=0x0000]
[   91.841639] amdgpu 0000:2d:00.0: amdgpu:      MORE_FAULTS: 0x0
[   91.841666] amdgpu 0000:2d:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0013 address=0xfe9fe000 flags=0x0020]
[   91.841674] amdgpu 0000:2d:00.0: amdgpu:      WALKER_ERROR: 0x5
[   91.841707] amdgpu 0000:2d:00.0: amdgpu:      PERMISSION_FAULTS: 0x3
[   91.841717] amdgpu 0000:2d:00.0: amdgpu:      MAPPING_ERROR: 0x1
[   91.841726] amdgpu 0000:2d:00.0: amdgpu:      RW: 0x0
[   91.908507] amdgpu 0000:2d:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0013 address=0xd7ddf000 flags=0x0000]
[   91.908546] amdgpu 0000:2d:00.0: AMD-Vi: Event logged [IO_PAGE_FAULT domain=0x0013 address=0xd7ddf000 flags=0x0020]
```
I still get an image. So, I'm not sure whether it is a serious error or not. But thought that I'd report it any way.

### Versions

(shark.venv) root@rocm:~/tmp# python collect_env.py
Collecting environment information...
PyTorch version: 2.2.0.dev20230913+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             16
On-line CPU(s) list:                0-15
Vendor ID:                          AuthenticAMD
Model name:                         AMD Ryzen 9 5950X 16-Core Processor
CPU family:                         25
Model:                              33
Thread(s) per core:                 1
Core(s) per socket:                 16
Socket(s):                          1
Stepping:                           2
Frequency boost:                    enabled
CPU max MHz:                        3400.0000
CPU min MHz:                        2200.0000
BogoMIPS:                           6799.72
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                     AMD-V
L1d cache:                          512 KiB (16 instances)
L1i cache:                          512 KiB (16 instances)
L2 cache:                           8 MiB (16 instances)
L3 cache:                           64 MiB (2 instances)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-15
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.0
[pip3] pytorch-lightning==2.1.0rc0
[pip3] torch==2.2.0.dev20230913+cpu
[pip3] torch-mlir==20230916.963
[pip3] torchmetrics==1.1.2
[pip3] torchvision==0.17.0.dev20230916+cpu
[conda] Could not collect

**Comment by zichguan-amd** [comment]
Hi @briansp2020, sorry for the late response and thanks for reporting this. It's hard to know what's going on just from the dmesg logs, and you seem to have CPU only PyTorch `PyTorch version: 2.2.0.dev20230913+cpu` which doesn't use ROCm. If you still experience this issue with the latest version of ROCm, feel free to provide more information on how you set up and run SHARK, and if the error occurs during any other graphics workloads.

**Comment by briansp2020** [comment]
I believe more recent ROCm have solved many problems. I have not tested SHARK recently but have used other AI projects with ROCm 6.2.x releases and they work much better.
