### ISSUE TITLE
torch.cuda.device() does not seem to have an effect

### ISSUE THREAD

**Issue by c0redumb** [ROCm/pytorch#1393]
### 🐛 Describe the bug

Using torch.cuda.device() to select the GPU, and it has no effect. GPU0 is always used, expecting GPU selected to be used. On the other hand, torch.cuda.set_device() works well. PyTorch documentation advice using torch.cuda.device() over set_device().

### Versions

Found when using ROCm PyTorch 6.0.2 official docker container on node with MI-60 GPUs. Other systems not tested.

**Comment by zichguan-amd** [comment]
Hi @c0redumb, `torch.cuda.device()` is a context manager, see https://github.com/pytorch/pytorch/issues/1608#issuecomment-303020201
