### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by lemairecarl** [ROCm/pytorch#565]
Hi! Thanks for making this project possible!

There does not seem to be any documentation for this repo. Even the README seems to be exactly the one from the original pytorch repo.

Is there a way to know which versions of PyTorch are compatible with ROCm ? According to the branches and releases of this repo, it appears that the latest supported version of PyTorch is v0.3.1. This is pretty old. Is this information correct? What's the best way to compare this fork with the original repo, in terms of versions ?

Thanks again!

**Comment by iotamudelta** [comment]
This repo is intentionally a straight fork from upstream - upstream is enabled for ROCm. The latest ROCm version we are using on the upstream CI is ROCm 2.9 (so this is upstream/master). I can personally also tell you that ROCm 2.10 works w/o problems. ROCm3.0 will require application of a patch referenced in other issues.

**Comment by lemairecarl** [comment]
I understand better now -- this repo is used to make PRs to the upstream repo. It's not clearly stated anywhere I've looked. I thought you were keeping a parallel source with significant changes to support ROCm. I'm pleasantly surprised that upstream supports ROCm "out of the box"! (not really out of the box as there's still that hipification to perform)

I also just looked at the wiki on this repo. I was wrong when I said there is no docs about this project. I really think there should be a link pointing to this wiki on the page about PyTorch on the ROCm site: 
https://rocm.github.io/pytorch.html

I'm an advisor on a committee looking to build a new cluster, and we are currently considering AMD GPUs. On that hypothetical cluster with AMD GPUs, our staff would provide a pytorch wheel that would work exactly as on the other machines that use CUDA (no Docker involved). Are you confident that option 4 (building from source) in the guide [Building-PyTorch-for-ROCm](https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Building-PyTorch-for-ROCm) is solid enough for our use case?

Thanks!

**Comment by iotamudelta** [comment]
I would recommend you use the docker method to obtain the wheel file, that's what we do internally. Subsequently, you can use that wheel file to install on the host. Building directly on the host is possible and there are external users that have successfully done so. However, PyTorch does require a bunch of build dependencies, correct incantation of build scripts, ... which I found to be much easier to get right inside the official docker environment.

**Comment by lemairecarl** [comment]
Ah, I see. I did not get the subtlety that I could use the docker image to get an independent wheel.

We plan to test PyTorch on a rented AMD GPU on the cloud. Any possible pitfalls come to mind?

Thanks again!

**Comment by iotamudelta** [comment]
Not so much pitfalls, upstream CI is testing on `gfx900` and `gfx906`, so I would strongly recommend those uarchs (you can get that from `/opt/rocm/bin/rocm_agent_enumerator`). Similarly, we are testing on Ubuntu16.04 and CentOS7, python3.6 so I'd recommend using these environments at least in the beginning. Note also that if you install torchvision via pip on a ROCm system, it'll try to delete and replace your torch with a CUDA torch, so build torchvision from source if you need that functionality (odds are, you do). Other than that report here if there are issues, we also have a few outstanding users here that share their own experiences and help.

**Comment by lemairecarl** [comment]
Thanks a lot! At first glance it seemed like PyTorch + ROCm was very risky, but this discussion gives me confidence. I will definitely report back any issues or insights.
