### ISSUE TITLE
Need help to investigate : RuntimeError: HIP error: hipErrorInvalidValue on (large) sum()

### ISSUE THREAD

**Issue by s-bernard** [ROCm/pytorch#639]
## 🐛 Bug

I built pytorch 1.5 from source with a Vega 56 and ROCm 3.3 on Archlinux. I ran the tests but the cuda test was failing with RuntimeError: HIP error: hipErrorInvalidValue.

Could you help me investigate what is the issue?

## To Reproduce

By analyzing the failing tests, I found that `sum()` was not working on cuda tensor wider than 130560: 

```
>>> torch.manual_seed(1);a=130560;b=1;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').sum().item()
136.0
>>> torch.manual_seed(1);a=130561;b=1;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').sum().item()
RuntimeError: HIP error: hipErrorInvalidValue
```

I tried to reshape it, if I sum everything, it still fails:
```
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum().item()
RuntimeError: HIP error: hipErrorInvalidValue
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(b,a).sum().item()
RuntimeError: HIP error: hipErrorInvalidValue
```

but if I do partial sum first, it may work ; if sum on axis 0, it fails, if on axis 1, it works.
```
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=0).sum().item()
RuntimeError: HIP error: hipErrorInvalidValue
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=0)
RuntimeError: HIP error: hipErrorInvalidValue

>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=1).sum().item()
268.0
```

Funny enough, if I reshape on `(b,a)` instead of `(a,b)`, it works on both axis:
```
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(b,a).sum(axis=0).sum().item()
268.0
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(b,a).sum(axis=1).sum().item()
268.0
```

I tried to transpose the failing shape, but still failing:
```
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).transpose(0,1).sum(axis=1)
RuntimeError: HIP error: hipErrorInvalidValue
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).transpose(0,1).sum(axis=0).sum().item()
268.0
```

Same if I use cuda after the transpose:
```
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).reshape(a,b).transpose(0,1).to(device='cuda').sum(axis=0)
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')
>>> torch.manual_seed(1);a=130560;b=2;torch.zeros(a*b).bernoulli_(0.001).reshape(a,b).transpose(0,1).to(device='cuda').sum(axis=1)
RuntimeError: HIP error: hipErrorInvalidValue
```

Finally, I searched which value of `a` works for different value of b, axis=0:
```
>>> torch.manual_seed(1);a=65280;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=0).sum().item()
136.0
>>> torch.manual_seed(1);a=65281;b=2;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=0).sum().item()
RuntimeError: HIP error: hipErrorInvalidValue

>>> torch.manual_seed(1);a=32640;b=4;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=0).sum().item()
136.0
>>> torch.manual_seed(1);a=32641;b=4;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=0).sum().item()
RuntimeError: HIP error: hipErrorInvalidValue

>>> torch.manual_seed(1);a=16320;b=8;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=0).sum().item()
166.0
>>> torch.manual_seed(1);a=16321;b=8;torch.zeros(a*b).bernoulli_(0.001).to(device='cuda').reshape(a,b).sum(axis=0).sum().item()
RuntimeError: HIP error: hipErrorInvalidValue
```

So the limits are 1 => 130560, 2-3 => 65280, 4-7 => 32640, 8-15 => 16320 which gives us the general rule.

Note : everything is working fine when it runs on CPU and I get the same result as the working line. I changed the seed, same behavior.

## Expected behavior

No Runtime Error.

## Environment

Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: No, ROCm

OS: Arch Linux
Kernel : 5.6.7-arch1-1
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: version 3.17.1

Python version: 3.8
ROCm 3.3, build from source: https://github.com/rocm-arch/rocm-arch
Vega 10 XL/XT [Radeon RX Vega 56/64]

Versions of relevant libraries:
[pip3] numpy==1.18.3
[pip3] torch==1.5.0a0+e4c78c6
[pip3] torchvision==0.5.0
[conda] not installed

Compile flag:
USE_DISTRIBUTED=OFF
CMAKE_C_COMPILER=/opt/rocm/hcc/bin/clang
CMAKE_CXX_COMPILER=/opt/rocm/hcc/bin/clang++

## Additional context

I tried on v1.4.1 tag, exactly the same issue.

**Comment by sunway513** [comment]
Hi @s-bernard a couple of comments for this issue:
- Archlinux is not officially supported by ROCm. For the supported OS by ROCm please refer to:
https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems

- PyTorch relies on all the underneath ROCm stacks to be functioning correctly. Here's the dependency list only for the user bit components:
ROCT-Thunk -- https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface
ROCr-Runtime -- https://github.com/RadeonOpenCompute/ROCR-Runtime
HIP -- https://github.com/ROCm-Developer-Tools/HIP
HCC (will soon be replaced by hipclang) -- https://github.com/RadeonOpenCompute/hcc 
OpenCL runtime -- https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime
MIOpen -- https://github.com/ROCmSoftwarePlatform/MIOpen
rocBLAS -- https://github.com/ROCmSoftwarePlatform/rocBLAS
rocRAND -- https://github.com/ROCmSoftwarePlatform/rocRAND.git
rocFFT -- https://github.com/ROCmSoftwarePlatform/rocFFT.git
rocPRIM -- https://github.com/ROCmSoftwarePlatform/rocPRIM.git
rocSPARSE -- https://github.com/ROCmSoftwarePlatform/rocSPARSE.git
rocTHRUST -- https://github.com/ROCmSoftwarePlatform/rocThrust
RCCL -- https://github.com/ROCmSoftwarePlatform/rccl

Hence, for such complicated software system, debugging from the top of the stack won't be feasible.

- I'd suggest to debug from HIP unit test:
https://github.com/ROCm-Developer-Tools/HIP/tree/master/tests
Once all the HIP unit test can pass, you can then move to the libraries and eventually on pytorch.

**Comment by s-bernard** [comment]
Hi @sunway513, thanks for your answer.

Yes, I know it’s not officially supported, that’s why I was asking for leads and not solutions ;).

Actually, you’re right, I tested HIP on https://github.com/ROCm-Developer-Tools/HIP-Examples and I’ve got some errors. See https://github.com/rocm-arch/rocm-arch/issues/138#issuecomment-622522617 if you’re curious.

I’ll continue my investigation from there. Thanks for your link on tests, it’ll help.

**Comment by ppanchad-amd** [comment]
@s-bernard Do you still need any assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by s-bernard** [comment]
Hi, we can close it. Thanks for asking.
