### ISSUE TITLE
Error while installing PyTorch from source (https://github.com/ROCmSoftwarePlatform/pytorch) when I use "release_1.6_PR41255" branch with backend BLIS

### ISSUE THREAD

**Issue by deepeshguru** [ROCm/pytorch#710]
## When I try to install pytorch from source with branch "release_1.6_PR41255" with backend BLIS instead of MKL, I am getting Error when I run "python setup.py install" inside pytorch directory, I am able to successfully install pytorch with blis with branch "release" and "1.6" but these branch has pytorch version 1.7, I want to install stable pytorch version 1.6 with BLIS:
-- Trying to find preferred BLAS backend of choice: blis
CMake Error at cmake/Dependencies.cmake:164 (message):
  Unrecognized BLAS option: blis
Call Stack (most recent call first):
  CMakeLists.txt:469 (include)

-- Configuring incomplete, errors occurred!
See also "/home/deepesh/exps/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/deepesh/exps/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 732, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/home/deepesh/exps/pytorch/tools/build_pytorch_libs.py", line 59, in build_caffe2
    rerun_cmake)
  File "/home/deepesh/exps/pytorch/tools/setup_helpers/cmake.py", line 329, in generate
    self.run(args, env=my_env)
  File "/home/deepesh/exps/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/deepesh/anaconda3/envs/blis_pytorch_1.6/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBLAS=blis', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/deepesh/exps/pytorch/torch', '-DCMAKE_PREFIX_PATH=/home/deepesh/anaconda3/envs/blis_pytorch_1.6/lib/python3.7/site-packages', '-DNUMPY_INCLUDE_DIR=/home/deepesh/.local/lib/python3.7/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/home/deepesh/anaconda3/envs/blis_pytorch_1.6/bin/python', '-DPYTHON_INCLUDE_DIR=/home/deepesh/anaconda3/envs/blis_pytorch_1.6/include/python3.7m', '-DPYTHON_LIBRARY=/home/deepesh/anaconda3/envs/blis_pytorch_1.6/lib/libpython3.7m.so.1.0', '-DTORCH_BUILD_VERSION=1.6.0a0+1d38148', '-DUSE_MKLDNN_CBLAS=ON', '-DUSE_NUMPY=True', '-DUSE_ROCM=0', '/home/deepesh/exps/pytorch']' returned non-zero exit status 1.
[CMakeError.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/5082836/CMakeError.log)
[CMakeOutput.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/5082837/CMakeOutput.log)

**Comment by sunway513** [comment]
Hi @deepeshguru , the quoted branch (release_1.6_PR41255) is for some other validation purpose.
Please refer to the following upstream branch for PyTorch 1.6 release:
https://github.com/pytorch/pytorch/tree/release/1.6

**Comment by deepeshguru** [comment]
Hi @sunway513 , same error comes, when I used BLIS instead of MKL with any release of PyTorch if I use source(https://github.com/pytorch/pytorch). I am able to build PyTorch1.6 with BLIS "https://github.com/ROCmSoftwarePlatform/pytorch/tree/restore_jit_tests_try2". I want to know "restore_jit_tests_try2" branch has stable pytorch 1.6 or not.

**Comment by sunway513** [comment]
@jeffdaily  can you help here?

**Comment by jeffdaily** [comment]
`Unrecognized BLAS option: blis`.  Please try cmake option `-DWITH_BLAS=FLAME`.

**Comment by jeffdaily** [comment]
You should be able to use either the upstream `release/1.6` branch or the same branch from our fork.

`git clone --recursive https://github.com/ROCmSoftwarePlatform/pytorch -b release/1.6`
or
`git clone --recursive https://github.com/pytorch/pytorch -b release/1.6`

**Comment by deepeshguru** [comment]
Hi @jeffdaily same error come after using -DWITH_BLAS=FLAME, I am using 
"**USE_ROCM=0 BLAS=blis WITH_BLAS=FLAME python setup.py install**" 
command to build pytorch with blis. and I have also exported blis path

export PATH=/home/deepesh/exps/blis2.2/include/blis:$PATH 
export LD_LIBRARY_PATH=/home/deepesh/exps/blis2.2/lib:$LD_LIBRARY_PATH 
export BLIS_HOME=/home/deepesh/exps/blis2.2 BLAS=blis USE_MKLDNN_CBLAS=ON WITH_BLAS=FLAME

**Comment by sunway513** [comment]
Hi @deepeshguru , can you try PyTorch 1.7 or 1.8 release branch? We have improved our CI coverage for PyTorch release branches after 1.6.

**Comment by ppanchad-amd** [comment]
Hi @deepeshguru. Closing ticket due to lack of activity.  Please feel free to re-open ticket if you still have issues with the latest ROCm? Thanks!
