### ISSUE TITLE
Pytorch 1.6.0 fails to build in rocm/pytorch:rocm3.7_ubuntu18.04_py3.6

### ISSUE THREAD

**Issue by boniek83** [ROCm/pytorch#734]
## 🐛 Bug
Pytorch 1.6.0 fails to build in container made from image: rocm/pytorch:rocm3.7_ubuntu18.04_py3.6

## To Reproduce

Dockerfile:
```
FROM rocm/pytorch:rocm3.7_ubuntu18.04_py3.6

USER root
RUN cd; git clone --depth 1 --branch v1.6.0 https://github.com/pytorch/pytorch.git
ENV PYTORCH_ROCM_ARCH=gfx906
ENV PYTORCH_BUILD_VERSION=1.6.0
ENV PYTORCH_BUILD_NUMBER=1
RUN cd; cd pytorch; git submodule update --init --recursive
RUN cd; cd pytorch;.jenkins/pytorch/build.sh
```
Error:
https://gist.github.com/boniek83/3fdf0b20a091bc52289df4ef042e60bb
## Expected behavior
Build should just work.

## Environment
 - ROCK: 3.7
 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): CentOS 7.8
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): See above
 - Python version: 3.6
 - CUDA/cuDNN version: 
 - GPU models and configuration: Radeon VII
 - Any other relevant information:

**Comment by boniek83** [comment]
git clone --depth 1 --branch 1.6 https://github.com/ROCmSoftwarePlatform/pytorch builds just fine

**Comment by ppanchad-amd** [comment]
Hi @boniek83. Closing ticket due to lack of activity. Please feel free to re-open ticket if you still see the issue with the latest ROCm. Thanks!
